name: CI

on:
  push:
    branches: [main, master]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Release Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Cache cargo registry & build artifacts
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            cli/target
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-release-

      - name: Build release
        run: |
          cargo build --release
          cargo test --release
          cargo clippy --release
          mv target/release/gaius gaius-linux-x86_64
        working-directory: cli

      - name: Upload binary artifact
        uses: actions/upload-artifact@v7
        with:
          name: gaius-linux-x86_64
          path: cli/gaius-linux-x86_64

      - name: Force update tag
        run: |
          git tag -f continuous
          git push origin continuous --force

      - name: Upload to continuous release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: continuous
          name: Continuous Release
          make_latest: false
          prerelease: true
          files: cli/gaius-linux-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
